#!/bin/bash

# Default username/passwd for docker registry
USERNAME=qraft
PASSWD=$(cat .initialPassword)
AUTH_FILE=auth/.htpasswd
S3_CREDENTIAL_FILE=.s3-credentials.csv

# 1. Define/Fetch AWS S3 Credentials (from .s3_credential.csv)
S3_ACCESSKEY=$(tail -n1 $S3_CREDENTIAL_FILE | awk -F ',' '{print $3}')
S3_SECRETKEY=$(tail -n1 $S3_CREDENTIAL_FILE | awk -F ',' '{print $4}')
S3_REGION="ap-northeast-2"
S3_BUCKET="qcontainer-imgs"
S3_ROOT_DIR=/registry


# 2. Configure Authorization for docker registry 
mkdir -p `dirname "$AUTH_FILE"`
if [ -f $AUTH_FILE ]; then
  echo "$AUTH_FILE already exists.. "
  echo "Available users are:"
  for AUTH in `cat $(pwd)/$AUTH_FILE`; do
    echo $AUTH
  done
else
  echo "New Master User for Docker Registry..."
  htpasswd -cBb $(pwd)/$AUTH_FILE $USERNAME $PASSWD
  cat $(pwd)/$AUTH_FILE

  ENCODED_PWD=$(echo -n "$USERNAME:$PASSWD" | base64)
  echo "enc password"
  echo $ENCODED_PWD
fi

# 3. Setup regisgtry container config.yml and docker-compose.yml
DIR_TMPL=yml.template.d
sed "s#__S3_ACCESS_KEY__#$S3_ACCESSKEY#g" $DIR_TMPL/.config.yml.template \
| sed "s#__S3_SECRET_KEY__#$S3_SECRETKEY#g" \
| sed "s#__S3_REGION__#$S3_REGION#g" \
| sed "s#__S3_BUCKET__#$S3_BUCKET#g" \
| sed "s#__S3_ROOT_DIR__#$S3_ROOT_DIR#g" > config.yml

sed "s#__S3_ACCESS_KEY__#$S3_ACCESSKEY#g" $DIR_TMPL/.docker-compose.yml.template \
| sed "s#__S3_SECRET_KEY__#$S3_SECRETKEY#g" \
| sed "s#__S3_REGION__#$S3_REGION#g" > docker-compose.yml

# 4. Docker Compose
docker-compose up -d
